version: '3.1'

services:
  mariadb:
    build: .
    container_name: selfconcept-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
