version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pages:/var/www/html
  selenium-hub:
    image: selenium/hub:4.21.0-20240521
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.21.0-20240521
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
