name: UI Tests

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_ui:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose curl
        pip install -r requirements.txt

    - name: Start services
      run: docker-compose -f containers/grid/docker-compose.yml -f containers/mariadb/docker-compose.yml up -d

    - name: Run tests
      run: pytest --alluredir=allure-results

    - name: Stop services
      if: always()
      run: docker-compose -f containers/grid/docker-compose.yml -f containers/mariadb/docker-compose.yml down
